"""
JWT Authentication Pattern for FastAPI
Python specialist reference for Phase II auth implementation
"""

from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from jose import JWTError, jwt
from datetime import datetime, timedelta
from typing import Optional
import os

# ==============================================================================
# JWT Configuration
# ==============================================================================

# Load from environment (.env file)
BETTER_AUTH_SECRET = os.getenv("BETTER_AUTH_SECRET")
JWT_ALGORITHM = "HS256"
JWT_EXPIRATION_HOURS = 168  # 7 days

security = HTTPBearer()


# ==============================================================================
# Token Verification (Backend receives tokens from Better Auth frontend)
# ==============================================================================

async def get_current_user_id(
    credentials: HTTPAuthorizationCredentials = Depends(security)
) -> str:
    """
    Extract and verify user ID from JWT Bearer token.

    ✅ PATTERN: Backend verifies tokens generated by Better Auth frontend.
    This is the ONLY way to get authenticated user_id.

    Raises:
        HTTPException 401: Invalid, expired, or missing token
    """
    token = credentials.credentials

    try:
        # Decode JWT using shared secret
        payload = jwt.decode(
            token,
            BETTER_AUTH_SECRET,
            algorithms=[JWT_ALGORITHM]
        )

        # Extract user ID from 'sub' claim
        user_id: str = payload.get("sub")

        if user_id is None:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid authentication credentials",
                headers={"WWW-Authenticate": "Bearer"},
            )

        return user_id

    except JWTError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )


# ==============================================================================
# Usage in FastAPI Routes
# ==============================================================================

from fastapi import APIRouter

router = APIRouter(prefix="/api/tasks")

# ✅ GOOD: Inject user_id via Depends
@router.get("/")
async def list_tasks(user_id: str = Depends(get_current_user_id)):
    """List tasks for authenticated user only."""
    # user_id is guaranteed valid from JWT
    tasks = get_tasks_from_db(user_id)  # Always filter by user_id!
    return tasks

@router.post("/")
async def create_task(
    task_data: TaskCreate,
    user_id: str = Depends(get_current_user_id)
):
    """Create task for authenticated user."""
    # Set user_id from JWT, NOT from request body
    new_task = Task(**task_data.dict(), user_id=user_id)
    # ... save to DB
    return new_task

# ❌ BAD: Don't do this!
@router.get("/{user_id}/tasks")  # Client can forge user_id in URL
async def list_tasks_bad(user_id: str):
    tasks = get_tasks_from_db(user_id)  # SECURITY VULNERABILITY!
    return tasks


# ==============================================================================
# Optional: Token Generation (if backend handles auth)
# ==============================================================================

def create_access_token(user_id: str, expires_delta: Optional[timedelta] = None) -> str:
    """
    Generate JWT token (only if backend handles authentication).
    In Phase II, Better Auth handles this on frontend.
    """
    if expires_delta:
        expire = datetime.utcnow() + expires_delta
    else:
        expire = datetime.utcnow() + timedelta(hours=JWT_EXPIRATION_HOURS)

    to_encode = {
        "sub": user_id,  # User ID in 'sub' claim
        "exp": expire,   # Expiration time
        "iat": datetime.utcnow()  # Issued at
    }

    encoded_jwt = jwt.encode(to_encode, BETTER_AUTH_SECRET, algorithm=JWT_ALGORITHM)
    return encoded_jwt


# ==============================================================================
# Testing Utilities
# ==============================================================================

def create_test_token(user_id: str = "test-user-123") -> str:
    """Create test JWT token for testing."""
    return create_access_token(user_id, timedelta(hours=1))

# Example usage in tests:
# headers = {"Authorization": f"Bearer {create_test_token('user-123')}"}
# response = client.get("/api/tasks", headers=headers)


# ==============================================================================
# KEY TAKEAWAYS
# ==============================================================================

"""
JWT AUTHENTICATION BEST PRACTICES:

1. ✅ ALWAYS use Depends(get_current_user_id) to get authenticated user
2. ✅ NEVER trust user_id from path params, query params, or request body
3. ✅ Extract user_id from JWT 'sub' claim only
4. ✅ Use shared BETTER_AUTH_SECRET between frontend and backend
5. ✅ Return 401 for invalid/expired tokens (not 403)
6. ✅ Use HS256 algorithm (symmetric key)
7. ✅ Don't leak error details (generic "Invalid credentials" message)
8. ✅ Add WWW-Authenticate header to 401 responses

SECURITY:
- The token is the ONLY source of truth for user identity
- Never allow client to specify user_id directly
- All protected routes MUST use Depends(get_current_user_id)
- Log auth failures for monitoring
- Rotate secrets periodically in production

BETTER AUTH INTEGRATION:
- Frontend (Better Auth) generates JWT tokens on login
- Backend verifies tokens using shared secret
- Backend extracts user_id from 'sub' claim
- Backend NEVER generates tokens in Phase II (Better Auth handles it)
"""
